# .travis.yml
dist: jammy
language: node_js

node_js:
  - '16'
  - '18'
  # Removed 'node' to avoid testing the very latest (which may require npm >= 11)

services:
  - xvfb  # If you need a browser environment

cache:
  npm: true

# before_install:
#   - npm install -g npm@latest  # Removed or commented out to avoid engine mismatch

install:
  - npm ci

script:
  - npm run test:single

notifications:
  email: false

branches:
  only:
    - main
