language: node_js
cache:
  directories:
    - ~/.npm
services:
  - xvfb
notifications:
  email: false
node_js:
  - '14'
before_script:
  - npm prune
script:
  - npm run test:single
branches:
  only:
    - master
